### ISSUE TITLE
Define a treshold for the card detection

### ISSUE THREAD

**Issue by ClemGerard** [datalab-mi/Basegun#431]
Définir un seuil de détection de carte en dessous duquel on considère qu'il n'y a pas de carte présente sur la photo, et donc que l'on affiche l'écran de rappel d'ajout d'une photo (missing card).

**Comment by ClemGerard** [comment]
test sur le dataset de l'IRCGN

Attention étiquette de saisie /!\ : confusion plus que plausible entre la carte pour la mesure et la carte de saisie.

**Comment by AurelienmartW** [comment]
First analysis: 0.5 seems to be a good threshold for card detection. Further analysis on S3 bucket basegun will give a more precise threshold

**Comment by AurelienmartW** [comment]
![Image](https://github.com/datalab-mi/Basegun/assets/92736328/813426ca-8c94-45e6-a6af-1c6b59ffcfa6)

Study on confidence score threshold for card detection.

card data -> 100 images of weapons with card
Nocard data -> 100 images of weapons without cards

Using a 0.5 thresholds for the confidence threshold of card detection:
81% of false positive removed
94% of true positive remained


Disclaimer -> those statistics are performed on particular datasets and not real basegun images from the app.
Another study should be realized in order to obtain a more precise threshold
